# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElixrTalentConnect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SideMenu'

  # Pods for ElixrTalentConnect

  target 'ElixrTalentConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ElixrTalentConnectUITests' do
    # Pods for testing
  end

end
